# Generated by Django 4.0.5 on 2022-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpAuth', '0003_attandee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizers',
            name='company_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
