# Generated by Django 4.1.4 on 2022-12-23 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SignUpAuth', '0004_organizers_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attandee',
            new_name='Attandees',
        ),
    ]
