# Generated by Django 4.1.4 on 2022-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpAuth', '0005_rename_attandee_attandees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandees',
            name='crypto_wallet_address',
            field=models.CharField(default=None, max_length=600),
            preserve_default=False,
        ),
    ]
