# Generated by Django 3.2.16 on 2022-12-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpAuth', '0005_rename_attandee_attandees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandees',
            name='private_crypto_address',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='attandees',
            name='public_crypto_address',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
