# Generated by Django 4.1.4 on 2023-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Qr code', max_length=120)),
                ('email', models.CharField(default='This is a Qr code used for check in', max_length=120)),
                ('q1', models.IntegerField(null=True)),
                ('q2', models.IntegerField(null=True)),
                ('has_given', models.BooleanField(default=False)),
            ],
        ),
    ]
