# Generated by Django 4.1.4 on 2023-09-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fan', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='has_given',
        ),
    ]
