# Generated by Django 4.1.4 on 2023-06-24 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Fan", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="myFan",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "public_crypto_address",
                    models.CharField(default=None, max_length=600),
                ),
                (
                    "private_crypto_address",
                    models.CharField(default=None, max_length=600),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QrCodeChecking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Qr code", max_length=120)),
                (
                    "description",
                    models.CharField(
                        default="This is a Qr code used for check in", max_length=120
                    ),
                ),
                (
                    "Qrcode",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                ("hash", models.CharField(default=None, max_length=300)),
                ("token_id", models.IntegerField(default=None)),
                ("checked", models.BooleanField(default=False)),
                (
                    "BlockNumber",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loyalfan",
            name="guest",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Fan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loyalfan",
            name="organizer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Club",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
