# Generated by Django 4.1.4 on 2023-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fan', '0003_remove_feedback_has_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='q3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q6',
            field=models.TextField(null=True),
        ),
    ]
