# Generated by Django 4.1.4 on 2023-06-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myfan",
            old_name="private_crypto_address",
            new_name="private_key",
        ),
        migrations.RenameField(
            model_name="myfan",
            old_name="public_crypto_address",
            new_name="public_key",
        ),
        migrations.DeleteModel(
            name="loyalFan",
        ),
    ]
