# Generated by Django 4.1.4 on 2024-01-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0004_feedback_q3_feedback_q4_feedback_q5_feedback_q6"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoWallets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(default=None, max_length=600)),
                ("private_key", models.CharField(default=None, max_length=600)),
                ("type", models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name="myfan",
            old_name="user",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="myfan",
            name="AuthWallet_busy",
        ),
        migrations.RemoveField(
            model_name="myfan",
            name="AuthWallet_private_key",
        ),
        migrations.RemoveField(
            model_name="myfan",
            name="AuthWallet_public_key",
        ),
        migrations.RemoveField(
            model_name="myfan",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="myfan",
            name="public_key",
        ),
        migrations.RemoveField(
            model_name="qrcodechecking",
            name="Qrcode",
        ),
        migrations.RemoveField(
            model_name="qrcodechecking",
            name="description",
        ),
        migrations.RemoveField(
            model_name="qrcodechecking",
            name="hash",
        ),
        migrations.RemoveField(
            model_name="qrcodechecking",
            name="id",
        ),
        migrations.RemoveField(
            model_name="qrcodechecking",
            name="name",
        ),
        migrations.AlterField(
            model_name="qrcodechecking",
            name="token_id",
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="QrCodeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Qr code", max_length=120)),
                (
                    "description",
                    models.CharField(
                        default="This is a Qr code used for check in", max_length=120
                    ),
                ),
                (
                    "Qrcode",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                ("hash", models.CharField(default=None, max_length=300)),
                (
                    "token_id",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Fan.qrcodechecking",
                    ),
                ),
            ],
        ),
    ]
