# Generated by Django 4.1.4 on 2023-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0004_rename_private_crypto_address_myfan_private_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfan",
            name="has_Payed",
            field=models.BooleanField(default=False),
        ),
    ]
