# Generated by Django 4.1.4 on 2024-01-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0005_cryptowallets_rename_user_myfan_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcodechecking",
            name="BlockNumber",
        ),
        migrations.AlterUniqueTogether(
            name="cryptowallets",
            unique_together={("public_key", "private_key")},
        ),
    ]
