# Generated by Django 5.0.2 on 2024-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Fan",
            "0005_rename_authwallet_private_key_myfan_gas_wallet_private_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodechecking",
            name="Qrcode",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="QrCodes"
            ),
        ),
    ]
