# Generated by Django 4.1.4 on 2023-08-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0005_myfan_has_payed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myfan",
            old_name="has_Payed",
            new_name="has_received_matic",
        ),
    ]
