# Generated by Django 4.1.4 on 2023-04-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventsCreated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=500)),
                ("event_date_time", models.DateTimeField()),
                ("event_maximum_capacity", models.PositiveIntegerField()),
                ("event_ticket_price", models.FloatField()),
                ("event_place", models.CharField(max_length=500)),
                ("event_description", models.TextField()),
                (
                    "event_banner",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                ("number_of_current_Fan", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EventsticketsMinted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NFT_owner_address", models.CharField(default=None, max_length=600)),
                ("NFT_token_id", models.CharField(default=None, max_length=600)),
                ("checkIn_Time", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
