# Generated by Django 4.1.4 on 2023-04-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="test",
        ),
    ]
