# Generated by Django 4.1.4 on 2023-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0004_auto_20230408_1115"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventscreated",
            old_name="event_banner",
            new_name="Team1Logo",
        ),
        migrations.RemoveField(
            model_name="eventscreated",
            name="event_description",
        ),
        migrations.RemoveField(
            model_name="eventscreated",
            name="event_name",
        ),
        migrations.AddField(
            model_name="eventscreated",
            name="SecondarySalesCapPrice",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="eventscreated",
            name="SecondarySalesRules",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name="eventscreated",
            name="Team1Name",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name="eventscreated",
            name="Team2Logo",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="eventscreated",
            name="Team2Name",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name="eventscreated",
            name="royaltyRate",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
