# Generated by Django 4.1.4 on 2023-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0005_rename_event_banner_eventscreated_team1logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
