# Generated by Django 4.1.4 on 2023-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0006_sportcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventscreated",
            name="category",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
