# Generated by Django 4.1.4 on 2023-04-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0007_eventscreated_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="clubData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stadiumImage",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                (
                    "teamLogo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
                ("clubName", models.CharField(default=None, max_length=600)),
                (
                    "clubId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubId",
                        to="Club.myclub",
                    ),
                ),
            ],
        ),
    ]
