# Generated by Django 4.1.4 on 2023-04-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Club", "0008_clubdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubdata",
            name="clubId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubId",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
