# Generated by Django 4.1.4 on 2023-06-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0009_alter_clubdata_clubid"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsticketsminted",
            name="TimeStamp",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
