# Generated by Django 4.1.4 on 2023-06-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0010_eventsticketsminted_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventscreated",
            name="EventBanner",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
