# Generated by Django 4.1.4 on 2023-06-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0013_remove_myclub_royaltyreceiveraddresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="myclub",
            name="RoyaltyReceiverAddresse",
            field=models.CharField(default=None, max_length=500),
        ),
    ]
