# Generated by Django 4.1.4 on 2023-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0014_myclub_royaltyreceiveraddresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsticketsminted",
            name="datebought",
            field=models.DateField(blank=True, null=True),
        ),
    ]
