# Generated by Django 4.1.4 on 2023-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0015_eventsticketsminted_datebought"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsticketsminted",
            name="checkIn_Time",
        ),
        migrations.AddField(
            model_name="eventsticketsminted",
            name="checked",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
