# Generated by Django 4.1.4 on 2023-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0016_remove_eventsticketsminted_checkin_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsticketsminted",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
