# Generated by Django 4.1.4 on 2023-04-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = []
