# Generated by Django 4.1.4 on 2023-04-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20230412_1639"),
    ]

    operations = []
