# Generated by Django 4.1.4 on 2023-04-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_auto_20230412_1640"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myusers",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
