# Generated by Django 3.2.16 on 2022-12-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myguests',
            name='id',
        ),
        migrations.AddField(
            model_name='myguests',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
