# Generated by Django 3.2.16 on 2022-12-27 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizers', '0002_auto_20221226_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_date_time', models.DateTimeField()),
                ('event_maximum_capacity', models.PositiveIntegerField()),
                ('event_ticket_price', models.FloatField()),
                ('event_place', models.CharField(max_length=500)),
                ('event_description', models.TextField()),
                ('event_banner', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('number_of_current_guests', models.PositiveIntegerField()),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
