# Generated by Django 3.2.16 on 2023-01-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizers', '0004_eventsticketsminted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsticketsminted',
            name='checkIn_Time',
            field=models.TimeField(default=None),
        ),
    ]
