# Generated by Django 3.2.16 on 2023-01-01 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Organizers', '0004_ticketsminted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsminted',
            name='mintingDate',
            field=models.DateField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
