# Generated by Django 3.2.16 on 2023-01-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizers', '0005_ticketsminted_mintingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsminted',
            name='mintingDate',
        ),
    ]
