# Generated by Django 3.2.16 on 2023-01-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizers', '0007_alter_eventsticketsminted_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsticketsminted',
            name='checkIn_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
