# Generated by Django 4.1.4 on 2022-12-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_date_time', models.DateTimeField()),
                ('event_maximum_capacity', models.PositiveIntegerField()),
                ('event_ticket_price', models.PositiveIntegerField()),
                ('event_place', models.CharField(max_length=500)),
                ('event_description', models.TextField()),
                ('number_of_current_guests', models.PositiveIntegerField()),
            ],
        ),
    ]
