# Generated by Django 4.1.4 on 2022-12-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCreated',
            new_name='EventsCreated',
        ),
    ]
