# Generated by Django 4.1.4 on 2022-12-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0002_rename_eventcreated_eventscreated'),
    ]

    operations = [
    ]
