# Generated by Django 4.1.4 on 2022-12-23 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventOrganizer', '0003_auto_20221223_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscreated',
            name='event_organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventscreated',
            name='event_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
