# Generated by Django 4.1.4 on 2022-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0004_eventscreated_event_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscreated',
            name='event_banner',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventscreated',
            name='event_date_time',
            field=models.DateTimeField(),
        ),
    ]
