# Generated by Django 4.1.4 on 2022-12-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0005_eventscreated_event_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscreated',
            name='event_banner',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
