# Generated by Django 4.1.4 on 2022-12-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0008_alter_eventscreated_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscreated',
            name='event_banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
