# Generated by Django 4.1.4 on 2022-12-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0009_alter_eventscreated_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscreated',
            name='event_ticket_price',
            field=models.FloatField(),
        ),
    ]
