# Generated by Django 3.2.16 on 2022-12-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0010_alter_eventscreated_event_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketsMinted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFT_owner_address', models.CharField(default=None, max_length=600)),
                ('NFT_owner_account', models.CharField(default=None, max_length=600)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventOrganizer.eventscreated')),
            ],
        ),
    ]
