# Generated by Django 4.1.4 on 2023-08-31 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('logo', models.ImageField(blank=True, default=None, max_length=600, null=True, upload_to='ClubsData')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default='2023-09-30 23:02')),
                ('place', models.CharField(max_length=500)),
                ('maximum_capacity', models.PositiveIntegerField()),
                ('maximum_ticket_per_account', models.PositiveIntegerField(default=None)),
                ('ticket_price', models.FloatField()),
                ('current_fan_count', models.PositiveIntegerField()),
                ('royalty_rate', models.PositiveIntegerField(default=None)),
                ('banner', models.ImageField(blank=True, default='None', null=True, upload_to='')),
                ('opposite_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.clubsdata')),
            ],
        ),
        migrations.CreateModel(
            name='myClub',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('RoyaltyReceiverAddresse', models.CharField(max_length=500, null=True)),
                ('club', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Club.clubsdata')),
            ],
        ),
        migrations.CreateModel(
            name='MintedTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_crypto_address', models.CharField(default=None, max_length=600)),
                ('token_id', models.CharField(default=None, max_length=600)),
                ('checked', models.BooleanField(default=False)),
                ('datebought', models.DateTimeField(default='2023-06-30 23:02')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='Club.event')),
                ('organizer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='Club.myclub')),
                ('owner_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_Attandee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.myclub'),
        ),
    ]
