# Generated by Django 4.1.4 on 2023-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclub',
            name='RoyaltyReceiver_private_key',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
