# Generated by Django 4.1.4 on 2023-06-24 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Club", "0002_initial"),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="myClub",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Number_of_events_created", models.PositiveIntegerField(default=0)),
                ("Company_name", models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="eventsticketsminted",
            name="NFT_owner_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_Attandee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventsticketsminted",
            name="event_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_id",
                to="Club.event",
            ),
        ),
        migrations.AddField(
            model_name="eventsticketsminted",
            name="organizer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_organizer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
