# Generated by Django 4.1.4 on 2024-01-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Club", "0002_myclub_royaltyreceiver_private_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myclub",
            old_name="user",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="event",
            name="opposite_team",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="mintedtickets",
            name="id",
        ),
        migrations.RemoveField(
            model_name="mintedtickets",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="mintedtickets",
            name="owner_account",
        ),
        migrations.RemoveField(
            model_name="mintedtickets",
            name="owner_crypto_address",
        ),
        migrations.RemoveField(
            model_name="myclub",
            name="RoyaltyReceiverAddresse",
        ),
        migrations.RemoveField(
            model_name="myclub",
            name="RoyaltyReceiver_private_key",
        ),
        migrations.RemoveField(
            model_name="myclub",
            name="club",
        ),
        migrations.AddField(
            model_name="event",
            name="team1",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1",
                to="Club.myclub",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="team2",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2",
                to="Club.myclub",
            ),
        ),
        migrations.AddField(
            model_name="mintedtickets",
            name="username",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_Attandee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="myclub",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=600,
                null=True,
                upload_to="ClubsData",
            ),
        ),
        migrations.AddField(
            model_name="myclub",
            name="name",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name="mintedtickets",
            name="token_id",
            field=models.CharField(
                default=None, max_length=600, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="ClubsData",
        ),
    ]
