# Generated by Django 4.1.4 on 2024-01-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0003_rename_user_myclub_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default="2023-09-30 23:02")),
                ("place", models.CharField(max_length=500)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "maximum_ticket_per_account",
                    models.PositiveIntegerField(default=None),
                ),
                ("price", models.FloatField()),
                ("current_fan_count", models.PositiveIntegerField()),
                ("royalty_rate", models.PositiveIntegerField(default=None)),
                (
                    "banner",
                    models.ImageField(
                        blank=True, default="None", null=True, upload_to=""
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team1",
                        to="Club.myclub",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team2",
                        to="Club.myclub",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mintedtickets",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_id",
                to="Club.events",
            ),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
