# Generated by Django 4.1.4 on 2023-06-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Club", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MintedTickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_crypto_address",
                    models.CharField(default=None, max_length=600),
                ),
                ("token_id", models.CharField(default=None, max_length=600)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_id",
                        to="Club.event",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_organizer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_Attandee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EventsticketsMinted",
        ),
    ]
