# Generated by Django 4.1.4 on 2023-06-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0003_initial"),
        ("Club", "0004_mintedtickets_delete_eventsticketsminted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mintedtickets",
            old_name="event_id",
            new_name="event",
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Club.myclub"
            ),
        ),
        migrations.AlterField(
            model_name="mintedtickets",
            name="owner_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_Attandee",
                to="Fan.myfan",
            ),
        ),
    ]
