# Generated by Django 4.1.4 on 2023-06-24 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Club", "0006_alter_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mintedtickets",
            name="owner_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_Attandee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
