# Generated by Django 4.1.4 on 2023-06-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0007_alter_mintedtickets_owner_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myclub",
            name="Number_of_events_created",
        ),
    ]
