# Generated by Django 4.1.4 on 2023-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0008_remove_myclub_number_of_events_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="datetime",
            field=models.DateTimeField(default="2023-06-30 23:02"),
        ),
    ]
