# Generated by Django 4.1.4 on 2023-06-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0009_alter_event_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myclub",
            old_name="Company_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="team1_logo",
        ),
        migrations.RemoveField(
            model_name="event",
            name="team1_name",
        ),
        migrations.AddField(
            model_name="myclub",
            name="logo",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Club.myclub"
            ),
        ),
    ]
