# Generated by Django 4.1.4 on 2023-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0010_rename_company_name_myclub_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=500)),
                (
                    "small_logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="ClubsData"
                    ),
                ),
                (
                    "medium_logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="ClubsData"
                    ),
                ),
            ],
        ),
    ]
