# Generated by Django 4.1.4 on 2023-06-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0011_clubsdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clubsdata",
            old_name="medium_logo",
            new_name="logo",
        ),
        migrations.RemoveField(
            model_name="clubsdata",
            name="small_logo",
        ),
    ]
