# Generated by Django 4.1.4 on 2023-06-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0012_rename_medium_logo_clubsdata_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="team2_logo",
        ),
        migrations.RemoveField(
            model_name="event",
            name="team2_name",
        ),
        migrations.AddField(
            model_name="event",
            name="opposite_team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Club.clubsdata",
            ),
            preserve_default=False,
        ),
    ]
