# Generated by Django 4.1.4 on 2023-06-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0013_remove_event_team2_logo_remove_event_team2_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myclub",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="myclub",
            name="name",
        ),
        migrations.AddField(
            model_name="myclub",
            name="club",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Club.clubsdata",
            ),
        ),
    ]
