# Generated by Django 4.1.4 on 2023-06-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0014_remove_myclub_logo_remove_myclub_name_myclub_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mintedtickets",
            name="organizer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_organizer",
                to="Club.myclub",
            ),
        ),
    ]
