# Generated by Django 4.1.4 on 2023-06-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0016_mintedtickets_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="mintedtickets",
            name="datebought",
            field=models.DateTimeField(default="2023-06-30 23:02"),
        ),
    ]
