# Generated by Django 4.1.4 on 2023-06-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0018_alter_mintedtickets_owner_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="myclub",
            name="RoyaltyReceiverAddresse",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
