# Generated by Django 4.1.4 on 2023-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0019_myclub_royaltyreceiveraddresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="datetime",
            field=models.DateTimeField(default="2023-09-30 23:02"),
        ),
    ]
