# Generated by Django 4.1.4 on 2023-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0020_alter_event_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="maximum_ticket_per_account",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
