# Generated by Django 4.1.4 on 2023-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0021_event_maximum_ticket_per_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubsdata",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=600,
                null=True,
                upload_to="ClubsData",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="banner",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to=""
            ),
        ),
    ]
