# Generated by Django 4.1.4 on 2023-04-08 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("Fan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="myFan",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "public_crypto_address",
                    models.CharField(default=None, max_length=600),
                ),
                (
                    "private_crypto_address",
                    models.CharField(default=None, max_length=600),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loyalfan",
            name="guest",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Fan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loyalfan",
            name="organizer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Club",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
