# Generated by Django 4.1.4 on 2023-06-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=120)),
                ("description", models.CharField(default=None, max_length=120)),
                ("user_Hash", models.CharField(default=None, max_length=300)),
                (
                    "Qrcode",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=""
                    ),
                ),
            ],
        ),
    ]
