# Generated by Django 4.1.4 on 2023-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0003_nftmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="nftmetadata",
            name="BlockNumber",
            field=models.IntegerField(default=None),
        ),
    ]
