# Generated by Django 4.1.4 on 2023-06-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0004_nftmetadata_blocknumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nftmetadata",
            name="Qrcode",
        ),
    ]
