# Generated by Django 4.1.4 on 2023-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0005_remove_nftmetadata_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="nftmetadata",
            name="tokenId",
            field=models.IntegerField(default=None),
        ),
    ]
