# Generated by Django 4.1.4 on 2023-06-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0006_nftmetadata_tokenid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nftmetadata",
            name="tokenId",
        ),
    ]
