# Generated by Django 4.1.4 on 2023-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0007_remove_nftmetadata_tokenid"),
    ]

    operations = [
        migrations.AddField(
            model_name="nftmetadata",
            name="Tokenid",
            field=models.IntegerField(default=None),
        ),
    ]
