# Generated by Django 4.1.4 on 2023-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0008_nftmetadata_tokenid"),
    ]

    operations = [
        migrations.CreateModel(
            name="QrCodeChecking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(default=None, max_length=300)),
                ("token_id", models.IntegerField(default=None)),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
    ]
