# Generated by Django 4.1.4 on 2023-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0010_qrcodechecking_qrcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NFTMetadata",
        ),
        migrations.AddField(
            model_name="qrcodechecking",
            name="BlockNumber",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="qrcodechecking",
            name="description",
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name="qrcodechecking",
            name="name",
            field=models.CharField(default=None, max_length=120),
        ),
    ]
