# Generated by Django 4.1.4 on 2023-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fan", "0011_delete_nftmetadata_qrcodechecking_blocknumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodechecking",
            name="description",
            field=models.CharField(
                default="This is a Qr code used for check in", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="qrcodechecking",
            name="name",
            field=models.CharField(default="Qr code", max_length=120),
        ),
    ]
