# Generated by Django 4.1.4 on 2023-06-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_myusers_date_joined_myusers_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myusers",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="myusers",
            name="last_name",
        ),
    ]
