# Generated by Django 4.1.4 on 2023-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_myusers_first_name_myusers_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="testMigrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=203)),
            ],
        ),
    ]
