# Generated by Django 4.1.4 on 2023-07-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_testmigrations"),
    ]

    operations = [
        migrations.DeleteModel(
            name="testMigrations",
        ),
    ]
